-- =====================================================================
-- 003_hetzner_shared_db.sql
-- Shared Hetzner Supabase DB (supabase.h.namekart.com) for NameBio + the
-- Comparable AI Agent. Apply manually with psql as postgres. Idempotent.
--
--   namebio.*     written by the NameBio service (was MySQL namebio_data on vps1).
--                 Table names match the JPA entities, so the service only needs
--                 `currentSchema=namebio` on its JDBC URL.
--   comparable.*  written/read by this agent (was stage Supabase public/ai_worker).
--                 Connect with search_path = comparable, public.
-- =====================================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS namebio;
CREATE SCHEMA IF NOT EXISTS comparable;

-- ---------------------------------------------------------------------
-- namebio
-- MySQL utf8mb4_0900_ai_ci is case-insensitive; Postgres is not, so the
-- (domain, sale_date, marketplace) unique key is now case-sensitive.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS namebio.namebio_sale (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         timestamp(6),
    domain             varchar(255) NOT NULL,
    marketplace        varchar(255),
    price              double precision,
    sale_date          date NOT NULL,
    ai_com_available   varchar(255),
    ai_com_checked_at  timestamp(6),
    com_available      varchar(255),
    com_checked_at     timestamp(6),
    CONSTRAINT uq_namebio_domain_date_marketplace UNIQUE (domain, sale_date, marketplace)
);
CREATE INDEX IF NOT EXISTS idx_namebio_sale_date           ON namebio.namebio_sale (sale_date);
CREATE INDEX IF NOT EXISTS idx_namebio_sale_date_price     ON namebio.namebio_sale (sale_date, price);
CREATE INDEX IF NOT EXISTS idx_namebio_sale_date_mktplace  ON namebio.namebio_sale (sale_date, marketplace);
CREATE INDEX IF NOT EXISTS idx_namebio_sale_date_price_id  ON namebio.namebio_sale (sale_date, price, id);
CREATE INDEX IF NOT EXISTS idx_namebio_sale_date_domain_id ON namebio.namebio_sale (sale_date, domain, id);
CREATE INDEX IF NOT EXISTS idx_namebio_sale_created_at     ON namebio.namebio_sale (created_at);

CREATE TABLE IF NOT EXISTS namebio.namebio_state (
    id                   bigint PRIMARY KEY,
    last_backfill_cursor date,
    updated_at           timestamp(6),
    credits_remaining    integer,
    credits_updated_at   timestamp(6),
    last_quota_alert_at  timestamp(6),
    last_quota_level     varchar(16)
);

CREATE TABLE IF NOT EXISTS namebio.namebio_api_usage (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        timestamp(6),
    credits_remaining integer,
    credits_spent     integer,
    error_message     varchar(1024),
    requested_date    date NOT NULL,
    sales_count       integer,
    status            varchar(16) NOT NULL
        CHECK (status IN ('ERROR', 'SKIPPED', 'SUCCESS')),
    trigger_source    varchar(32) NOT NULL
        CHECK (trigger_source IN ('BACKFILL', 'DAILY', 'MANUAL', 'MONTH_BACKFILL'))
);
CREATE INDEX IF NOT EXISTS idx_api_usage_created_at ON namebio.namebio_api_usage (created_at);

CREATE TABLE IF NOT EXISTS namebio.namebio_pending_month (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month_start date NOT NULL UNIQUE
);

-- ---------------------------------------------------------------------
-- comparable
-- pgvector lives in `public` on this instance.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS comparable.domain_embeddings (
    id        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    content   text,
    metadata  jsonb,
    embedding public.vector(384)
);
CREATE INDEX IF NOT EXISTS idx_domain_embeddings_meta_domain
    ON comparable.domain_embeddings ((metadata->>'domain'));

CREATE TABLE IF NOT EXISTS comparable.domain_enrichment (
    domain              text PRIMARY KEY,
    sld                 text,
    tld                 text,
    primary_category    text,
    secondary_category  text,
    keywords            jsonb       DEFAULT '[]'::jsonb,
    tokens              jsonb       DEFAULT '[]'::jsonb,
    descriptions        jsonb       DEFAULT '[]'::jsonb,
    confidence          real,
    source              text,
    status              text        NOT NULL DEFAULT 'queued_for_llm',
    queue_reason        text,
    embedded            boolean     NOT NULL DEFAULT false,
    enrichment_version  int         NOT NULL DEFAULT 1,
    embedding_version   int         NOT NULL DEFAULT 1,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_domain_enrichment_status        ON comparable.domain_enrichment (status);
CREATE INDEX IF NOT EXISTS idx_domain_enrichment_enr_version   ON comparable.domain_enrichment (enrichment_version);
CREATE INDEX IF NOT EXISTS idx_domain_enrichment_emb_version   ON comparable.domain_enrichment (embedding_version);
CREATE INDEX IF NOT EXISTS idx_domain_enrichment_queue_reason  ON comparable.domain_enrichment (queue_reason);
CREATE INDEX IF NOT EXISTS idx_domain_enrichment_embed_pending ON comparable.domain_enrichment (embedded, status);

CREATE TABLE IF NOT EXISTS comparable.llm_enrichment_queue (
    id            bigserial PRIMARY KEY,
    domain        text        NOT NULL UNIQUE,
    queue_reason  text        NOT NULL,
    priority      int         NOT NULL DEFAULT 0,
    attempts      int         NOT NULL DEFAULT 0,
    status        text        NOT NULL DEFAULT 'pending',
    last_error    text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_llm_queue_drain
    ON comparable.llm_enrichment_queue (status, priority DESC, created_at ASC);

CREATE TABLE IF NOT EXISTS comparable.ingest_state (
    id                   int PRIMARY KEY DEFAULT 1,
    last_backfill_cursor date,
    last_daily_date      date,
    updated_at           timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ingest_state_singleton CHECK (id = 1)
);

COMMIT;
